[env:esp32-1248]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps =
    zinggjm/GFX_Root@^2.0.0
    zinggjm/GxEPD2@^1.6.5
build_flags =
    -DDISPLAY_GDEY1248Z51
    -DDISPLAY_SKIP_HIBERNATE
board_build.f_cpu = 160000000L
monitor_speed = 115200
upload_speed = 921600
